spring:
  application:
    name: ZeroLog
  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    level: "%5p [${spring.application.name:},%mdc]"

springdoc:
  api-docs:
    path: /api-docs

sensitives: userId,SSN,name,firstname,lastname,email,address

